### ISSUE TITLE
TessBaseAPI init failed.

### ISSUE THREAD

**Issue by GHLab** [adaptech-cz/Tesseract4Android#2]
Hi.
I called TessBaseAPI.init after copy eng.traineddata but return value is false.
Do you know what problem is?

**Comment by Robyer** [comment]
Hi, where did you get `eng.traineddata` from? To which folder did you copied it? How do you call `TessBaseAPI.init()`?

I believe your problem is with wrong traineddata version/type or wrong path or wrong TessBaseAPI.init() call. In any case, you can set breakpoints in Android Studio and debug it where exactly it fails.

**Comment by GHLab** [comment]
@Robyer I downloaded the data here https://github.com/tesseract-ocr/tessdata/tree/4.0.0 
As debug result I think the data file is located in right folder.
And I called the init method like below.

`try {
            tessBaseApi = new TessBaseAPI();
        } catch (Exception e) {
            Log.e(TAG, e.getMessage());
            if (tessBaseApi == null) {
                Log.e(TAG, "TessBaseAPI is null. TessFactory not returning tess object.");
            }
        }

        boolean success = tessBaseApi.init(TESSBASE_PATH, DEFAULT_LANGUAGE, TessBaseAPI.OEM_TESSERACT_ONLY);`

Although I changed OEM value to OEM_TESSERACT_ONLY or OEM_LSTM_ONLY or OEM_TESSERACT_LSTM_COMBINED but all return value is false.
Can you help me to fix this problem?

**Comment by GHLab** [comment]
Sorry it was my mistake. I resolved this issue by checking android read external storage permission.
Thank you.

**Comment by Robyer** [comment]
No problem, I glad you solved it.
