### ISSUE TITLE
Expose Deskew from Skew

### ISSUE THREAD

**Issue by SubhamTyagi** [adaptech-cz/Tesseract4Android#28]
Currently only findSkew is exposed in Skew.java , Deskew is also equally important which is not exposed by this lib. Kindly make available them. 

`PIX *  pixDeskew (PIX *pixs, l_int32 redsearch)`
`PIX *  pixFindSkewAndDeskew (PIX *pixs, l_int32 redsearch, l_float32 *pangle, l_float32 *pconf)`

**Comment by Robyer** [comment]
@SubhamTyagi Please prepare a pull request to make this available.

**Comment by Robyer** [comment]
@SubhamTyagi Hi, I was looking into this a bit more. I realized that you don't really need this function exposed, because all it does, is 1) detect the skew (findSkew method is exposed in java) 2) rotate the image based on the skew value (rotate method is also exposed in java).

So basically Deskew is just a shorthand for both these operations and you just call Skew and then Rotate yourself. Or am I missing something?

**Comment by SubhamTyagi** [comment]
Hi, @Robyer
 > basically Deskew is just a shorthand for both these operations and you just call Skew and then Rotate yourself.

Yes Deskew is shorthand for these functions.

**Comment by Robyer** [comment]
This is implemented now. Thanks.
