### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by ken2812221** [adaptech-cz/Tesseract4Android#34]
https://github.com/adaptech-cz/Tesseract4Android/blob/e97a1c62c11b794e908466871c268a2e4143fea6/tesseract4android/src/main/cpp/tesseract/tessbaseapi.cpp#L138
The native_data_t is newed in here, but not deleted in anywhere. Maybe we should use end() or finalize() function to delete nat?

**Comment by Robyer** [comment]
@ken2812221 Good catch. As I am looking at the code, this `native_data_t` is created by call from java constructor. Method `end()` can't be used for destroying that data, because current API expects that you can call `end()` and then `init()` again, on the same instance of the java object. Also, `finalize()` method shouldn't be used as it's not reliable (there is no gurantee when (or if) it will be called). Though we can use it as a backup, in case client forget to call method to delete it.

So we need to:
a) Modify API and create `native_data_t` in `init()` and delete it in `end()`.
b) Add new method, like `destroy()`, that would explicitly delete the `native_data_t`.

I think (b) is better, since (a) breaks backwards compatibility and somewhat limits the usage of the API.
But having to call `end()` and then also `destroy()` is weird, so the destroy method should first call `end()`. Then most clients will just use `destroy()`, which feels natural.

I just wonder why nobody didn't notice this issue before? This API is pretty old.

**Comment by Robyer** [comment]
I have used combination of the two variants. `end()` is now renamed to `recycle()` in which `native_data_t` is deleted. Re-initialization after calling `recycle()` is not possible anymore. In case someone wants to re-initialize Tesseract and specify some init-variables (which was only one documented reason why calling `end()` and `init()` again was useful), he can now use new `init()` method that takes the configuration variables directly.
