### ISSUE TITLE
Bug in the documentation

### ISSUE THREAD

**Issue by frist008** [adaptech-cz/Tesseract4Android#36]
```kotlin
	/**
	 * Calls End() and finalizes native data. Must be called on object destruction.
	 */
	private native void nativeRecycle(long mNativeData);
```

Replace `end` to `recycle` - TessBaseAPI

**Comment by Robyer** [comment]
@frist008 This is actually correct documentation, because internally (in the native code) this method truly calls End() on the native Tesseract instance.
https://github.com/adaptech-cz/Tesseract4Android/blob/92e07828776e8dd8e73b74e0948c61d6b71ef6c0/tesseract4android/src/main/cpp/tesseract/tessbaseapi.cpp#L466-L485
