### ISSUE TITLE
pixReadMemTiff - function not present

### ISSUE THREAD

**Issue by jkryszyn** [adaptech-cz/Tesseract4Android#40]
Hello,
after building this library and invoking it on the device I get the following error:

``` 
Error in pixReadMemTiff: function not present
Error in pixReadMem: tiff: no pix returned
Error in pixaGenerateFontFromString: pix not made
Error in bmfCreate: font pixa not made
```

what can be done about it?

**Comment by Robyer** [comment]
Currently ony libjpeg and libpng is supported. If you want to add support for tiff images, you need to:

1. Add libtiff library here: https://github.com/adaptech-cz/Tesseract4Android/tree/master/tesseract4android/src/main/cpp
2. Create CMakeLists.txt file and configure how to build it (get inspiration in libjpeg / libpng folders)
3. Modify main CMakeLists.txt to compile also the libtiff library: https://github.com/adaptech-cz/Tesseract4Android/blob/master/tesseract4android/src/main/cpp/CMakeLists.txt
4. Modify Leptonica's CMakeLists.txt to enable support for the libtiff library: https://github.com/adaptech-cz/Tesseract4Android/blob/master/tesseract4android/src/main/cpp/leptonica/CMakeLists.txt
5. Modify all the java files here https://github.com/adaptech-cz/Tesseract4Android/tree/master/tesseract4android/src/main/java/com/googlecode and add line to load also the libtiff library.
6. Compile the project.

**Comment by Robyer** [comment]
@jkryszyn Have you resolved your issue by what I wrote above?

**Comment by jkryszyn** [comment]
@Robyer actually it turned out that I don't need libtiff and I can live with those errors.

**Comment by Robyer** [comment]
Ok, I'll close this issue then as I think TIFF format is generally not used on Android devices anyway.

(but if more people that needs TIFF support are reading this, feel free to comment, so I can reconsider)

**Comment by LeviMarvin** [comment]
@Robyer Hello! I'm using this library for programming. I got the same error from Tesseract, could you support TIFF format image? maybe this will solve some problem of text recognition like inaccurate result and more

**Comment by Robyer** [comment]
@LeviMarvin Hi, the steps I described in https://github.com/adaptech-cz/Tesseract4Android/issues/40#issuecomment-1073878195 should be easy to do as you can get inspiration from existing libpng/libjpeg support. So if you want, you can do it yourself and then send me a pull-request.

On the other hand, may I ask what is your use-case with the TIFF images? Since Android cameras produce images in JPEG, YUV and RAW format, you must get your TIFF images from somewhere else, which seems like you are building some very specialized app. In that case for 99 % of users of this library it will just bloat its size, so I would probably compile by default without TIFF support and let these users compile it themselves in case they would need TIFF.

Finally, I don't believe your inaccurate recognition results will be solved by different format - you can already provide lossless images (like PNG, or any other format provided as Bitmap directly) to Tesseract. And even if you use JPEG, I don't think the results will be significantly worse - to quickly verify, you can download desktop Tesseract version and let it recognize same image saved in TIFF or PNG and JPEG and check for yourself whether you will get better results or not.

Let me know what do you think.
