### ISSUE TITLE
PSM_SINGLE_BLOCK_VERT_TEXT doesn't work for Japanese

### ISSUE THREAD

**Issue by 0xbad1d3a5** [adaptech-cz/Tesseract4Android#42]
I'm getting some pretty non-sensical results when I try to use PSM_SINGLE_BLOCK_VERT_TEXT with Japanese text. Back when I used to use tess-two instead of this library, it seemed to work. I'm using jpn.traineddata and jpn_vert.traineddata in https://github.com/tesseract-ocr/tessdata_best. And the way I'm initializing the APIs is here: https://github.com/0xbad1d3a5/Kaku/blob/master/app/src/main/java/ca/fuwafuwa/kaku/Ocr/OcrRunnable.kt

![image](https://user-images.githubusercontent.com/878158/161924818-9f6bd84f-26ba-4b2f-b75c-6f06c6940537.png)

But yeah, I'm not entirely sure what's wrong here. Any hints/tips on how to debug this issue? Thanks!

**Comment by Robyer** [comment]
Hi, since Tesseract4Android is only a wrapper around Tesseract, you need to use official Tesseract channels for help in this case.

But since you mentioned tess-two, you were using old Tesseract 3.xx engine. With Tesseract 4+ there is new LSTM based engine, but you can still easily switch to use the old one. Just use it like this `init(dataPath, language, OEM_TESSERACT_ONLY)` (by default is uses new `OEM_LSTM_ONLY`). This way you should get old behavior (with pros and cons of the old engine).

**Comment by Robyer** [comment]
I'm closing the issue now as I don't see any further action here.
