### ISSUE TITLE
Adding Santali tessdata file (sat.traineddata)

### ISSUE THREAD

**Issue by Prasanta-Hembram** [adaptech-cz/Tesseract4Android#54]
Hi, there is a tessdata file provided by [Indic-Ocr](https://github.com/indic-ocr) for Santali language-- https://github.com/indic-ocr/tessdata/tree/master/sat . Don't know which version they used, is it possible to integrate it here ??

**Comment by Robyer** [comment]
Hi, since that file is 7 years old, it will definitely be for the old Tesseract engine. However you can use that in current Tesseract too, because Tesseract still ships with both the LSTM and old engine.

Try the [sample](https://github.com/adaptech-cz/Tesseract4Android/tree/master/sample) project, add your wanted *.traineddata file into [assets](https://github.com/adaptech-cz/Tesseract4Android/tree/master/sample/src/main/assets) directory and update the [Config.java](https://github.com/adaptech-cz/Tesseract4Android/blob/master/sample/src/main/java/cz/adaptech/tesseract4android/sample/Config.java) accordingly.

I verified that your `sat.traineddata` works there even without changing the `TESS_ENGINE` constant, but with some traineddata I previously tried I had to use the `TessBaseAPI.OEM_TESSERACT_ONLY` instead.
