### ISSUE TITLE
error: cannot access TessBaseAPI import com.googlecode.tesseract.android.TessBaseAPI;

### ISSUE THREAD

**Issue by Moubassher** [adaptech-cz/Tesseract4Android#61]
I get this error when I use the latest release (4.6.1):
```
bad class file: C:\Users\Dell\.gradle\caches\transforms-3\772d6328fab52940435810f05606380e\transformed\tesseract4android-4.6.0-api.jar(/com/googlecode/tesseract/android/TessBaseAPI.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by Moubassher** [comment]
aha yes. Java 11 is also not compatible. The maximum is Java 8 for Android (Oracle removed internal APIs that Android depends on starting Java 9 during the Oracle Vs Google legal mess, and this is why Google has been trying so hard to phase out Java, by the way). And thank you for your hard work.

**Comment by Robyer** [comment]
Btw I see that I used the Java 17 for the previous version (4.5.0) too, so last one working for you should be 4.4.0, correct?

**Comment by Robyer** [comment]
I tried to use the current version in older Android project configured for Java 11 or even Java 8, and it works.
So now I am thinking that you have some different problem...

How are you using this library in your project? Especially as I see `tesseract4android-4.6.0-api.jar` in your error which looks strange, because Android libraries are distributed as AAR and not JAR.

**Comment by Moubassher** [comment]
> Btw I see that I used the Java 17 for the previous version (4.5.0) too, so last one working for you should be 4.4.0, correct?

Version (4.5.0) gave me the same error. Should try 4.4.0 and get back to you. (But how is it working with you? this is mystifying to me. Android won't touch a Java version higher than Java 8 AFAIK).

**Comment by Moubassher** [comment]
> I tried to use the current version in older Android project configured for Java 11 or even Java 8, and it works. So now I am thinking that you have some different problem...
> 
> How are you using this library in your project? Especially as I see `tesseract4android-4.6.0-api.jar` in your error which looks strange, because Android libraries are distributed as AAR and not JAR.

I found the jar part strange too, actually. I only added the implementation to gradle, and hadn't written any code, just copied the simplest usage you described and got the error.

**Comment by Robyer** [comment]
You can use newer Java APIs on Android, you just need to use recent version of Android Gradle Plugin and configure the wanted version in your `build.gradle` as this:

```
android {
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}
}
```
More info: https://developer.android.com/build/jdks#compileSdk

Could you try to open and build the [sample](https://github.com/adaptech-cz/Tesseract4Android/tree/master/sample) project? Because maybe the problem is in your old Android Studio and/or old version of Java on your system?

**Comment by Moubassher** [comment]
> You can use newer Java APIs on Android, you just need to use recent version of Android Gradle Plugin and configure the wanted version in your `build.gradle` as this:
> 
> ```
> android {
> 	compileOptions {
> 		sourceCompatibility JavaVersion.VERSION_17
> 		targetCompatibility JavaVersion.VERSION_17
> 	}
> }
> ```
> 
> More info: https://developer.android.com/build/jdks#compileSdk
> 
> Could you try to open and build the [sample](https://github.com/adaptech-cz/Tesseract4Android/tree/master/sample) project? Because maybe the problem is in your old Android Studio and/or old version of Java on your system?

I did not know that. Thank you very much. The problem is gone. 
Thanks again, for your hard work and support.
