### ISSUE TITLE
How to support parsing Chinese？

### ISSUE THREAD

**Issue by Sky24n** [adaptech-cz/Tesseract4Android#67]

**Comment by Robyer** [comment]
I expect you just need to use correct traineddata files from https://github.com/tesseract-ocr/tessdata/tree/4.0.0 and then select that language when calling init().

Maybe there is more to properly configure it for Chinese, but since this library is just a wrapper around the Tesseract itself, you should consult their docs/support. Check their main repo: https://github.com/tesseract-ocr/tesseract
